import Head from 'next/head'
import Dashboard from '@/components/dashboard'
import Link from 'next/link'

export default function Home() {

  return (
    <>
      <Head>
        <title>Dash 4growth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="mt-10 grid center text-center">
        <h1>Bem vindo ao Dashboard</h1>
        <h1>4 growth br</h1>
      <Link href="/pagina2" className="bg-green-400 text-white w-auto mx-20">Acessar</Link>
      </main>
    </>
  )
}
