import Head from 'next/head'
import { CustomPage } from '@/components/page'


export default function Home() {
  return (
    <>
      <Head>
        <title>Dash 4growth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <CustomPage/>
    </>
  )
}
