import Head from 'next/head'
import Dashboard from '@/components/dashboard'

export default function Home() {

  return (
    <>
      <Head>
        <title>Dash 4growth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Dashboard/>
    </>
  )
}
